name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Build Firefox Plugin
        run: |
          npm run build:firefox -- --env build_number=1.2.${{ github.run_number }}
        shell: bash

      - name: Package Firefox
        run: |
          cd dist
          zip -r ../namida-ff.xpi ./*
          rm -rf dist

      - name: Upload Firefox Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-plugin
          path: namida-ff.xpi

      - name: Build Chrome Plugin
        run: |
          npm run build:chrome -- --env build_number=1.2.${{ github.run_number }}
        shell: bash

      - name: Package Chrome
        run: |
          cd dist
          zip -r ../namida-chrome.crx ./*
          cd ..
          rm -rf dist

      - name: Upload Chrome Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-plugin
          path: namida-chrome.crx
